PhosphorIcon widget updated to allow generic IconData.
phosphor-icons/flutter pull request #26
Opened 2023-08-15 21:52 UTC by luis901101

Current implementation of `PhosphorIcon` widget requires a `PhosphorIconData` which avoids using the widget for any type of Icon. This PR allows using `PhosphorIcon` with generic `IconData`

2023-11-03 02:32 UTC, rurickdev requested changes
Please run the dart format to adjust the style of the code, otherwise looks good to me

2023-11-03 02:32 UTC, rurickdev commented on lib/src/phosphor_icon.dart
> +      });
run dart formatter

2023-11-03 04:10 UTC, luis901101 commented on lib/src/phosphor_icon.dart
> +      });
Done

2023-11-03 04:12 UTC, luis901101 commented
> Please run the dart format to adjust the style of the code, otherwise looks good to me
> 
> also don't forget to update the changelog and the version to 2.0.1

I didn't updated the version nor the changelog so you can decide how to describe the changes in the changelog and what's the version number best fit the next release.

2023-11-03 18:21 UTC, rurickdev commented
> I didn't updated the version nor the changelog so you can decide how to describe the changes in the changelog and what's the version number best fit the next release.

Commonly we follow the versions from the icons pack, but this mostly only do mayor changes and because this PR includes a fix with the stack alignment I'm ok incrementing the last number as semantic versioning suggest, buuuut because you added the constraint in the flutter and dart version making it a breaking change semantic says that the first number should be updated which would break the sync with the icons pack version.

> ```yaml 
>  sdk: ">=3.0.0 <4.0.0"
>  flutter: '>=3.3.0'
> ```

I think the PR could be reworked removing the syntactic sugar of the `super` keyword and restoring the sdk and flutter constraints, maybe change the constraints for sdk just bigger than using `^`, and in the next icon pack release we include the breaking change and use the sugar

@rektdeckard what do you think?

and for the changelog I would put something like
> Fix bad alignment for duotone icons

2023-11-03 18:27 UTC, luis901101 commented
> > I didn't updated the version nor the changelog so you can decide how to describe the changes in the changelog and what's the version number best fit the next release.
> 
> Commonly we follow the versions from the icons pack, but this mostly only do mayor changes and because this PR includes a fix with the stack alignment I'm ok incrementing the last number as semantic versioning suggest, buuuut because you added the constraint in the flutter and dart version making it a breaking change semantic says that the first number should be updated which would break the sync with the icons pack version.
> 
> > ```yaml
> >  sdk: ">=3.0.0 <4.0.0"
> >  flutter: '>=3.3.0'
> > ```
> 
> I think the PR could be reworked removing the syntactic sugar of the `super` keyword and restoring the sdk and flutter constraints, maybe change the constraints for sdk just bigger than using `^`, and in the next icon pack release we include the breaking change and use the sugar
> 
> @rektdeckard what do you think?
> 
> and for the changelog I would put something like
> 
> > Fix bad alignment for duotone icons

Agree, you can commit with the necessary changes for the proper versioning alignment.

2023-11-04 06:18 UTC, rurickdev commented
So, I fixed the version constraint and took the opportunity to fix the issue with web, and the change log is updated.
I'll do the merge and and publish the new version

btw, here is a screenshot of the example app working on (from left to right) Chrome, Android, iOS and MacOS

![Screenshot 2023-11-03 at 23 58 21](https://github.com/phosphor-icons/flutter/assets/6403537/de215443-8fb5-4000-a2d3-6f3d1f969e27)

2023-11-04 06:21 UTC, rurickdev approved these changes

2023-11-04 06:22 UTC, merged